FROM node:14-alpine

WORKDIR /app
# Install ganache-cli globally
RUN npm install -g ganache-cli
# Set the default command for the image
CMD ["ganache-cli", "--mnemonic", "track mosquito measure very tag diet entry rate peanut tumble rely lion", "-h", "0.0.0.0"]
