name: Run Tests Contract

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Want to run the solidity tests?'
        # Input has to be provided for the workflow to run
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://npm.pkg.github.com/
    - name: Login to Docker
      run: echo "${{ secrets.NPM_TOKEN }}" | docker login -u vince-lynch --password-stdin ghcr.io
    - name: Run Tests
      run: npm run start
      working-directory: libs/test-solidity-contract
